### ISSUE TITLE
Half Hole Question

### ISSUE THREAD

**Issue by tinyboxxx** [blackketter/teensy4_header_breakout#1]
Hi, great work, but I have few questions.

I asked few local PCB manufacturer, they charge these half holes very expensive, ￥150 to 300 RMB (more than 25 USD). When without half holes, it only cost 5 to 25 RMB.

So why OSH Park can do it in reasonable price? Should I cutting it myself?

Thanks.

**Comment by blackketter** [comment]
Sorry, just saw this question now.  OSHPark doesn't guarantee the hole castellations, so the feature isn't officially supported.  That said, the 1.6mm thickness boards seem to work ok, but the 0.8mm process at OSHPark have not worked well.  
Getting boards made this way (especially with internal cutouts) is harder and takes more time, that's why they are more expensive.  I suspect that the price could come down if they were made in high enough volume.
